import type { Metadata, Viewport } from 'next';
import '@/styles/globals.css';
import { satoshi } from '@/styles/fonts';
import TopBanner from '@/components/layout/Banner/TopBanner';
import TopNavbar from '@/components/layout/Navbar/TopNavbar';
import Footer from '@/components/layout/Footer';
import HolyLoader from 'holy-loader';
import Providers from './providers';
import QueryProvider from '@/providers/QueryProvider';
import { headers } from 'next/headers';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Shopco',
  description: 'Generated by create next app'
};

export const viewport: Viewport = {
  themeColor: '#000000'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get the current path from headers
  const headersList = headers();
  const pathname = headersList.get('x-pathname') || '';
  const isAdmin = pathname.startsWith('/admin');

  if (isAdmin) {
    return (
      <html lang="en" className="h-full">
        <body className={`${satoshi.className} h-full antialiased`}>
          <HolyLoader color="#868686" />
          <Providers>{children}</Providers>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={satoshi.className}>
        <HolyLoader color="#868686" />
        <TopBanner />
        <Providers>
          <TopNavbar />
          {children}
        </Providers>
        <Footer />
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
